cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add'),
    path('view/', views.view_cart, name='view_cart'),
    path('remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update-quantity/<int:cart_item_id>/', views.update_quantity, name='update_quantity'),
    path('convert-to-order/', views.convert_cart_to_order, name='convert_to_order'),
]

drop_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from drop_app import settings
# Nao mudar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('product-registration/', views.product_registration, name='product_registration'),
    path('product-registration/create/', views.product_create, name='product_create'),
    path('product-list/', views.product_list, name='product_list'),
    path('product-update/<int:pk>', views.product_update, name='product_update'),
    path('delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('search-by-type/<str:type>/', views.search_by_type, name='search_by_type'),
    path('product-details/<int:product_id>/', views.product_details, name='product_details'),
]

product/models.py
from django.db import models
from enum import Enum

class ProductType(Enum):
    MOBILE = 'Mobile'
    TV = 'TV'
    CAMERA = 'Camera'
    LAPTOP = 'Laptop'
    TABLET = 'Tablet'
    SPEAKER = 'Speaker'

class CustomProduct(models.Model):
    name = models.CharField(max_length=255)
    product_type = models.CharField(max_length=20, choices=[(tag.name, tag.value) for tag in ProductType])
    description = models.CharField(max_length=255)
    price = models.FloatField()
    stock = models.IntegerField()
    image = models.ImageField(upload_to='product_images/', blank= True, null=True)

    def __str__(self):
        return self.name

    @classmethod
    def get_all_products(cls):
        return cls.objects.all()

    @classmethod
    def search_by_productname(cls, name):
        return cls.objects.filter(name__icontains=name)

    @classmethod
    def search_by_producttype(cls, product_type):
        return cls.objects.filter(product_type__icontains=product_type)


    @classmethod
    def filter_by_available_stock(cls):
        return cls.objects.filter(stock__gt=0)

product/forms.py
import re   
from django import forms
from .models import CustomProduct, ProductType
from PIL import Image

class CustomProductForm(forms.ModelForm):
    class Meta:
        model = CustomProduct
        fields = '__all__'

    widgets = {
        'name': forms.TextInput(attrs={}),
        'product_type': forms.Select(choices=[(tag.name, tag.value) for tag in ProductType]),
        'description': forms.TextInput(attrs={}),
        'price': forms.NumberInput(attrs={}),
        'stock': forms.NumberInput(attrs={}),
        'image': forms.ClearableFileInput(attrs={}),
    }

    def add_placeholder(self, field_name, placeholder_text, *length_restrictions):
        widget_attrs = {'placeholder': placeholder_text}

        if length_restrictions:
            widget_attrs['maxlength'] = length_restrictions[0]
            if len(length_restrictions) > 1:
                widget_attrs['minlength'] = length_restrictions[1]

        self.fields[field_name].widget.attrs.update(widget_attrs)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].label = 'Nome'
        self.fields['name'].help_text = 'Nome do produto não pode conter caracteres especiais.'
        self.fields['name'].error_messages = {
            'required': 'Por favor, preencha o campo Nome.',
            'max_length': 'O nome não pode ter mais de 255 caracteres.',
        }
        self.add_placeholder('name', 'Digite o nome do produto', 255)

        self.fields['description'].label = 'Descrição'
        self.fields['description'].error_messages = {
            'required': 'Por favor, preencha o campo Descrição.',
            'max_length': 'A descrição não pode ter mais de 255 caracteres.',
        }
        self.add_placeholder('description', 'Digite a descrição do produto', 255)

        self.fields['price'].label = 'Preço'
        self.fields['price'].help_text = 'Digite apenas numeros para o preço do produto.'
        self.fields['price'].error_messages = {
            'required': 'Por favor, preencha o campo Preço.',
        }
        self.add_placeholder('price', '20,00')

        self.fields['stock'].label = 'Estoque'
        self.fields['stock'].help_text = 'Digite apenas nuemros para a quantidade de estoque do produto.'
        self.fields['stock'].error_messages = {
            'required': 'Por favor, preencha o campo Estoque.',
        }
        self.add_placeholder('stock', '100')


    def clean_name(self):
        name = self.cleaned_data['name']

        if not re.match(r'^[a-zA-Z0-9\s]+$', name):
            raise forms.ValidationError('O nome não pode conter caracteres especiais.')

        return name

    # def isfloat(value):
    #     try:
    #         float(value)
    #         return True
    #     except ValueError:
    #         return False


    # def clean_price(self):
    #     price = self.cleaned_data['price']
    #     if not price.isfloat():
    #         raise ValidationErr('Por favor, insira apenas números para o preço.')
    #     return price
    

    # def clean_stock(self):
    #     stock = self.cleaned_data['stock']
    #     if not stock.isdigit():
    #         raise ValidationErr('Por favor, insira apenas números para a quantidade em estoque.')
    #     return stock


    def clean_image(self):
        image = self.cleaned_data.get('image')

        if image:
            try:
                img = Image.open(image)
                img.verify()  # Verifica se é uma imagem válida
                img.close()

                # Verifique o tamanho máximo da imagem (por exemplo, 5 MB)
                max_size = 5 * 1024 * 1024  # 5 MB em bytes
                if image.size > max_size:
                    raise forms.ValidationError('A imagem não pode ter mais de 5 MB.')

            except Exception as e:
                raise forms.ValidationError('A imagem é inválida. Certifique-se de enviar um arquivo de imagem válido.')

        return image
    
class ProductListForm(forms.Form):
    q = forms.CharField(label='', required=False, widget=forms.TextInput(attrs={'placeholder': 'Pesquisar Produtos...'}))

product/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.core.serializers import serialize
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .forms import CustomProduct, CustomProductForm, ProductListForm

def is_admin(user):
    return user.is_authenticated and user.is_staff

def home(request):
    products = CustomProduct.objects.all()
    form = ProductListForm(request.GET)
    query = form['q'].value()
    if query:
        products = CustomProduct.search_by_productname(query)
    else:
        products = CustomProduct.get_all_products()

    if is_ajax(request):
        data = serialize('json', products)
        return JsonResponse(data, safe=False)

    return render(request, 'product/pages/home.html', {'products': products})


# @user_passes_test(is_admin)
@login_required(login_url="product:home")
def product_registration(request):
    register_form_data = request.session.get('register_form_data', None)
    form = CustomProductForm(register_form_data)
    return render(request, 'product/pages/product-registration-form.html',{
        'form': form,
        'form_action': reverse('product:product_create'),
    })


# @user_passes_test(is_admin)
@login_required(login_url="product:home")
def product_create(request):
    if not request.POST:
        return HttpResponse(status=400)

    POST = request.POST
    request.session['register_form_data'] = POST
    form = CustomProductForm(POST)

    if form.is_valid():
        form.save()
        messages.success(request, 'Produto criado com sucesso.')
        del(request.session['register_form_data'])
        
    return redirect('product:product_registration')


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

# @user_passes_test(is_admin)
@login_required(login_url="product:home")
def product_list(request):
    form = ProductListForm(request.GET)
    query = form['q'].value()
    if query:
        products = CustomProduct.search_by_productname(query)
    else:
        products = CustomProduct.get_all_products()

    if is_ajax(request):
        data = serialize('json', products)
        return JsonResponse(data, safe=False)

    return render(request, 'product/pages/product-list.html', {'products': products, 'query': query, 'form': form})


# @user_passes_test(is_admin)
@login_required(login_url="product:home")
def product_update(request, pk):
    product = get_object_or_404(CustomProduct, pk=pk)

    if request.method == 'POST':
        form = CustomProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Produto atualizado com sucesso.')
            return redirect('product:product_list')
    else:
        form = CustomProductForm(instance=product)

    return render(request, 'product/pages/product-update-form.html', {'form': form, 'instance': product})


# @user_passes_test(is_admin)
@login_required(login_url="product:home")
def delete_product(request, pk):
    product = get_object_or_404(CustomProduct, pk=pk)

    if request.method == 'POST':
        product.delete()
        messages.success(request, 'Produto excluído com sucesso.')

        # Redirecionar para a lista de produtos após a exclusão
        return redirect('product:product_list')

    # Se a requisição não for POST, redirecionar para a lista de produtos
    return redirect('product:product_list')

def search_by_type(request, type):
    products = CustomProduct.search_by_producttype(type)

    if is_ajax(request):
        data = serialize('json', products)
        return JsonResponse(data, safe=False)

    return render(request, 'product/pages/home.html', {'products': products, 'product_type': type})

def product_details(request, product_id):
    product = get_object_or_404(CustomProduct, pk=product_id)

    if request.method == 'POST':
        return redirect('product:product_details', product_id=product_id)

    return render(request, 'product/pages/product_details.html', {'product': product})

product/templates/product/pages/home.html
{% extends 'global/base.html' %}

{% block content %}
{% include 'global/partials/search.html' %}
<div class="container">
  <h1 class="mt-4">Produtos em Destaque</h1>
  <div id="cart-message" style="display: none;"></div>
  <div class="row">
    {% for product in products %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow" style="display: flex; align-items: center;">
          {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="image-container " width="100px" height="100px" style="max-height: 100px;">
          {% else %}
            Sem imagem
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <span class="text-muted">{{ product.price }}</span>
              <a href="{% url 'product:product_details' product_id=product.id %}">Ver Detalhes</a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

product/templates/product/pages/product-list.html
{% extends 'global/base.html' %}

{% block content %}
<div class="container">
  <h1 class="mt-4">Lista de Produtos</h1>

  <div class="search-bar">
    <form id="search-form" method="GET" action="{% url 'product:product_list' %}">
      {{ form.q }}
      <button type="submit" class="btn btn-primary p-2">
        <i class="ml-1 fa-solid fa-magnifying-glass"></i>Pesquisar
      </button>
    </form>
  </div>

  {% if query %}
    <p id="search-query">Resultados para a pesquisa: "{{ query }}"</p>
  {% endif %}
  {% csrf_token %}
  <div class="table-responsive">
    <table class="table table-striped table-hover table-dark table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Imagem</th>
          <th scope="col">Código</th>
          <th scope="col">Nome</th>
          <th scope="col">Descrição</th>
          <th scope="col">Preço</th>
          <th scope="col">Estoque</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for product in products %}
        <tr>
          <td>
            {% if product.image %}
              <img src="{{ product.image.url }}" alt="{{ product.name }}" class="image-container " style="max-height: 50px;">
            {% else %}
              Sem imagem
            {% endif %}
          </td>
          <td>{{ product.id }}</td>
          <td>{{ product.name }}</td>
          <td>{{ product.description }}</td>
          <td>{{ product.price }}</td>
          <td>{{ product.stock }}</td>
          <td>
            <a href="{% url 'product:product_update' pk=product.pk %}" class="btn btn-warning btn-sm">
              <i class="fas fa-edit"></i>
            </a>
            <form id="product-table" method="POST" action="{% url 'product:delete_product' pk=product.pk %}">
              {% csrf_token %}
              <button class="btn btn-danger btn-sm" type="submit" title="Excluir Produto">
                <i class="fas fa-trash"></i>
              </button>
            </form>            
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

product/templates/product/pages/product-registration-form.html
{% extends 'global/base.html' %} 
{% block content %}
<div class="container">
  <script src="https://unpkg.com/imask"></script>
  <h1 class="mt-4">Cadastro de Produtos</h1>

  <div class="main-content container">
    {% if form.errors %}
    <div class="form-content form-content-grid">
      <div class="form-group">
        <div class="message message-error">{{ form.errors }}</div>
      </div>
    </div>
    {% endif %}
    <form
      action="{% url 'product:product_create' %}"
      id="registerForm"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div class="form-content form-content-grid">
        {% for field in form %}
        <div class="form-group">
          <label for="{{field.id_for_label }}">{{field.label}}</label>
          {% if field.name == 'image' %}
            <input type="file" name="{{ field.name }}" accept="image/*">
          {% else %}
            {{field}}
          {% endif %}
          {% if field.help_text %}
          <p class="help_text">{{field.help_text}}</p>
          {% endif %}
          {{field.errors}}
        </div>
        {% endfor %}
      </div>
      <div class="form-content form-content-grid">
        <div class="form-group">
          <button type="submit">Cadastrar</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

product/templates/product/pages/product-update-form.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="container">
    <h1 class="mt-4">Atualizar Produtos</h1>

    <div class="main-content container">
      {% if form.errors %}
      <div class="form-content form-content-grid">
        <div class="form-group">
          <div class="message message-error">
            {{ form.errors }}
          </div>
        </div>
      </div>
      {% endif %}
      <form action="{% url 'product:product_update' pk=instance.pk %}" id="updateform" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-content form-content-grid">
          {% for field in form %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% if field.name == 'image' %}
                <input type="file" name="{{ field.name }}" accept="image/*">
                {% if instance.image %}
                  <img src="{{ instance.image.url }}" alt="{{ instance.name }}" class="img-thumbnail" style="max-height: 50px;">
                {% else %}
                  Sem imagem
                {% endif %}
              {% else %}
                {{ field }}
              {% endif %}
            </div>
          {% endfor %}
        </div>
        <div class="form-content form-content-grid">
          <div class="form-group">
            <button type="submit">Atualizar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

product/templates/product/pages/product_details.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="container">
    <h1 class="mt-4">Detalhes do Produto</h1>
    <div class="card-details">
      <div class="card-details-body">
        <h5 class="card-details-title">{{ product.name }}</h5>
        <p class="card-details-text">{{ product.description }}</p>
        <p class="card-details-text">Preço: R$ {{ product.price }}</p>
        <form method="post" action="{% url 'cart:add' product_id=product.id %}">
            {% csrf_token %}
            <label for="quantity">Quantidade:</label>
            <input type="number" name="quantity" value="1" min="1">
            <!-- Adicione um campo hidden para enviar a quantidade -->
            <input type="hidden" name="form_quantity" id="form_quantity" value="0">
            <button type="submit" class="btn btn-primary">Adicionar ao Carrinho</button>
        </form>
      </div>
    </div>
  </div>
  <script>
    // Atualiza o valor do campo hidden antes de enviar o formulário
    document.querySelector('form').addEventListener('submit', function() {
      document.getElementById('form_quantity').value = document.querySelector('input[name="quantity"]').value;
    });
  </script>
{% endblock %}