cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add'),
    path('view/', views.view_cart, name='view_cart'),
    path('remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update-quantity/<int:cart_item_id>/', views.update_quantity, name='update_quantity'),
    path('convert-to-order/', views.convert_cart_to_order, name='convert_to_order'),
]

drop_app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from drop_app import settings
# Nao mudar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('process-order/<int:pk>/', views.process_order, name='process_order'),
    path('order-confirmation/<int:pk>/', views.order_confirmation, name='order_confirmation'),
    path('order-list/', views.order_list, name='order_list'),
    path('order-detail/<int:pk>/', views.order_detail, name='order_detail'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('product-registration/', views.product_registration, name='product_registration'),
    path('product-registration/create/', views.product_create, name='product_create'),
    path('product-list/', views.product_list, name='product_list'),
    path('product-update/<int:pk>', views.product_update, name='product_update'),
    path('delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('search-by-type/<str:type>/', views.search_by_type, name='search_by_type'),
    path('product-details/<int:product_id>/', views.product_details, name='product_details'),
]

order/models.py
from django.db import models
from drop_app import settings
from product.models import CustomProduct

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders')
    created_at = models.DateTimeField(auto_now_add=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_completed = models.BooleanField(default=False)
    shipping_address = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'Pedido {self.pk}'
    
    def update_total_amount(self):
        # Atualizar o total_amount do pedido com base nos OrderItems associados
        self.total_amount = sum(item.subtotal for item in self.orderitem_set.all())
        self.save()
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(CustomProduct, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.subtotal = self.quantity * self.price
        super().save(*args, **kwargs)

        self.order.update_total_amount()
        self.order.save()

    def __str__(self):
        return f'Pedido {self.pk}'

order/forms.py
from django import forms

class CreditCardForm(forms.Form):
    name= forms.CharField(label='Nome como esta no catão', max_length=255, min_length=12)
    card_number = forms.CharField(label='Número do Cartão', max_length=19)
    expiration_date = forms.DateField(label='Data de Expiração', widget=forms.SelectDateWidget)
    cvv = forms.CharField(label='CVV', max_length=3)

order/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .models import Order, OrderItem
from .forms import CreditCardForm

@login_required(login_url="user:login_view")
def process_order(request, pk):

    order = get_object_or_404(Order, user=request.user, is_completed=False, pk=pk)
    form = CreditCardForm(request.GET)
    if request.method == 'POST':
        return redirect('order:process_order', pk=order.id)

    context = {
        'order': order,
        'form': form
    }

    return render(request, 'orders/pages/process-order.html', context)

@login_required(login_url="user:login_view")
def order_confirmation(request, pk):
    try:
        order = Order.objects.get(id=pk)
    except Order.DoesNotExist:
        return render(request, 'orders/pages/order-not-found.html')

    if request.method == 'POST':
        credit_card_form = CreditCardForm(request.POST)
        if credit_card_form.is_valid():
            # Lógica para processar os dados do cartão de crédito
            # ...S

            # Marque o pedido como concluído
            order.is_completed = True
            order.save()

            return redirect('order:order_confirmation', pk=order.id)

    else:
        credit_card_form = CreditCardForm()

    context = {
        'order': order,
        'total_amount': order.total_amount,
        'credit_card_form': credit_card_form,
    }

    return render(request, 'orders/pages/order-confirmation.html', context)

@login_required(login_url="user:login_view")
def order_list(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, 'orders/pages/order-list.html', {'orders': orders})


@login_required(login_url="user:login_view")
def order_detail(request, pk):
    # Tenta obter o pedido do usuário
    order = get_object_or_404(Order, id=pk, user=request.user)

    # Obtém os itens do pedido
    order_items = OrderItem.objects.filter(order=order)

    # Calcular subtotal e total_price
    total_price = 0
    for order_item in order_items:
        order_item.subtotal = order_item.quantity * order_item.product.price
        total_price += order_item.subtotal
        order_item.save()  # Salvar a alteração no subtotal

    return render(request, 'orders/pages/order-detail.html', {'order': order, 'order_items': order_items, 'total_price': total_price})

order/templates/orders/pages/order-confirmation.html
{% extends 'global/base.html' %}

{% block content %}
<div class="container">
    <h1>Confirmação de Pedido</h1>
    <p>Seu pedido foi concluído com sucesso!</p>

    <h2>Detalhes do Pedido</h2>
    <p>Total do Pedido: R$ {{ total_amount }}</p>

    <!-- Back to Home Button -->
    <a href="{% url 'product:home' %}" class="btn btn-primary">Voltar para a Página Inicial</a>
</div>
{% endblock %}

order/templates/orders/pages/order-detail.html
<!-- orders/templates/orders/pages/order_detail.html -->
{% extends 'global/base.html' %}

{% block content %}
  <div class="container">
    <h1>Detalhes do Pedido</h1>
    
    <!-- Lista de itens comprados -->
    <h2>Itens Comprados</h2>
    <table class="table">
    <thead>
        <tr>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Preço Unitário</th>
        <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        {% for order_item in order.orderitem_set.all %}
        <tr>
            <td>{{ order_item.product.name }}</td>
            <td>{{ order_item.quantity }}</td>
            <td>R$ {{ order_item.price }}</td>
            <td>R$ {{ order_item.subtotal }}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

    <!-- Exiba os detalhes do pedido -->
    <p>Data do Pedido: {{ order.created_at }}</p>
    <p>Total do Pedido: R$ {{ order.total_amount }}</p>
    <p>Endereço de Entrega: {{ order.shipping_address }}</p>

    <form method="post" action="{% url 'order:process_order' pk=order.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Pagar Pedido</button>
      </form>
  </div>
{% endblock %}

order/templates/orders/pages/order-list.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="container">
    <h1>Lista de Pedidos</h1>
    
    {% if orders %}
      <table class="table">
        <thead>
          <tr>
            <th>ID do Pedido</th>
            <th>Data do Pedido</th>
            <th>Status</th>  <!-- Adicione a coluna de status -->
            <!-- Adicione mais colunas conforme necessário -->
          </tr>
        </thead>
        <tbody>
          {% for order in orders %}
            <tr>
              <td><a href="{% url 'order:order_detail' pk=order.id %}">{{ order.id }}</a></td>
              <td>{{ order.created_at }}</td>
              <td>{% if order.is_completed %}Finalizado{% else %}Não Finalizado{% endif %}</td>  <!-- Exibir o status -->
              <!-- Adicione mais colunas conforme necessário -->
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>Nenhum pedido encontrado.</p>
    {% endif %}
  </div>
{% endblock %}

order/templates/orders/pages/process-order.html
{% extends 'global/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'global/css/order.css' %}" type="text/css">
{% block content %}
<div class="container">
    <h2>Informações do Cartão de Crédito</h2>
    <form method="POST" class="credit-card-form" action="{% url 'order:order_confirmation' pk=order.id %}">
        {% csrf_token %}
        
        <div class="form-group">
          <label for="{{ form.name.id_for_label }}">Nome:</label>
          {{ form.name }}
        </div>

        <div class="form-group">
            <label for="{{ form.card_number.id_for_label }}">Número do Cartão:</label>
            {{ form.card_number }}
        </div>

        <div class="form-group">
            <label for="{{ form.expiration_date.id_for_label }}">Data de Expiração:</label>
            <input type="text" name="expiration_date" id="{{ form.expiration_date.id_for_label }}" class="form-control" placeholder="MM/AAAA" maxlength="7" data-mask="00/0000" required>
        </div>

        <div class="form-group">
            <label for="{{ form.cvv.id_for_label }}">CVV:</label>
            {{ form.cvv }}
        </div>

        <button type="submit" class="btn btn-primary">Confirmar Pedido</button>
    </form>
</div>

<script src="https://unpkg.com/imask"></script>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var cardNumberInput = document.getElementById('{{ credit_card_form.card_number.id_for_label }}');
  var expirationDateInput = document.getElementById('{{ credit_card_form.expiration_date.id_for_label }}');
  var cvvInput = document.getElementById('{{ credit_card_form.cvv.id_for_label }}');

  var cardNumberMask = IMask(cardNumberInput, {
    mask: '0000-0000-0000-0000'
  });

  var expirationDateMask = IMask(expirationDateInput, {
    mask: '00/0000'
  });

  var cvvMask = IMask(cvvInput, {
    mask: '000'
  });
});
</script>

{% endblock %}